version: "3.4"

services:
  redis_common:
    image: redis:5.0
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - "./redis.conf:/usr/local/etc/redis/redis.conf"
      - "./data:/data"
    ports:
      - "6379:6379"
